# Basic Information 
title: Mutahar Ali
position: PhD Student
affiliation: University of California, Irvine (UCI)
email: mutahara (at) uci (dot) edu

# Search Engine Optimization (SEO)
keywords: Mutahar Ali, UCI, LUMS, Computer Science, Security
description: Mutahar Ali is a PhD student at University of California, Irvine (UCI). His research interests lie in security and privacy of emerging computing technologies.

# Links 
cv_link: assets/files/CV.pdf
github_link: https://github.com/mutahar789
linkedin: https://www.linkedin.com/in/mutahar789
medium: https://medium.com/@mutahar789

# Images
avatar: ./assets/img/me.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
